/**
 * Data fetching layer.
 *
 * Most endpoints read from static JSON files generated by the scraper.
 * A few endpoints (scores, upcoming, boxscores, scorebar) try a Vercel
 * API route first for fresher data, falling back to static on error.
 */

async function dataFetch(path) {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Data fetch error ${res.status}: ${path}`);
  return res.json();
}

/** Try the API route first; fall back to static JSON on any error. */
async function liveOrStatic(apiPath, staticPath) {
  try {
    const res = await fetch(apiPath);
    if (!res.ok) throw new Error(res.status);
    return await res.json();
  } catch {
    return dataFetch(staticPath);
  }
}

/** Try static first; fall back to API if static is missing (e.g. live/recent games). */
async function staticOrLive(staticPath, apiPath) {
  try {
    const res = await fetch(staticPath);
    if (!res.ok) throw new Error(res.status);
    return await res.json();
  } catch {
    const res = await fetch(apiPath);
    if (!res.ok) throw new Error(`API fetch error ${res.status}: ${apiPath}`);
    return res.json();
  }
}

export const api = {
  // ── Live API routes (with static fallback) ──────────────────────────────
  scores:    () => liveOrStatic("/api/scores",    "/data/scores.json"),
  upcoming:  () => liveOrStatic("/api/upcoming",  "/data/upcoming.json"),
  boxscore:  (gameId) => staticOrLive(`/data/boxscores/${gameId}.json`, `/api/boxscores/${gameId}`),
  boxscoreLive: (gameId) => dataFetch(`/api/boxscores/${gameId}`),
  scorebar:  () => liveOrStatic("/api/scorebar", "/data/scores-live.json"),

  // ── Static-only (from scraper / transaction agent) ─────────────────────
  scoresStatic:   () => dataFetch("/data/scores.json"),
  boxscoreStatic: (gameId) => dataFetch(`/data/boxscores/${gameId}.json`),
  standings: () => dataFetch("/data/standings.json"),
  leaders:   () => dataFetch("/data/leaders.json"),
  players:   (teamId) => dataFetch(`/data/players/${teamId}.json`),
  roster:    (teamId) => dataFetch(`/data/rosters/${teamId}.json`),
  teamMoves: (teamId) => dataFetch(`/data/team-moves/${teamId}.json`),
  fightingMajors: () => dataFetch("/data/fighting-majors.json"),
  gameAttendance: () => dataFetch("/data/game-attendance.json"),
};
