// All 30 ECHL teams with primary/secondary colors and logo URLs
export const teams = {
  74: {
    id: 74,
    name: "Adirondack Thunder",
    city: "Adirondack",
    abbreviation: "ADK",
    division: "North",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/74.png",
  },
  66: {
    id: 66,
    name: "Allen Americans",
    city: "Allen",
    abbreviation: "ALN",
    division: "Central",
    conference: "Western",
    primaryColor: "#002868",
    secondaryColor: "#BF0D3E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/66.png",
  },
  10: {
    id: 10,
    name: "Atlanta Gladiators",
    city: "Atlanta",
    abbreviation: "ATL",
    division: "South",
    conference: "Eastern",
    primaryColor: "#C8102E",
    secondaryColor: "#000000",
    logoUrl: "https://assets.leaguestat.com/echl/logos/10.png",
  },
  107: {
    id: 107,
    name: "Bloomington Bison",
    city: "Bloomington",
    abbreviation: "BLM",
    division: "Central",
    conference: "Western",
    primaryColor: "#003087",
    secondaryColor: "#7A7C80",
    logoUrl: "https://assets.leaguestat.com/echl/logos/107.png",
  },
  5: {
    id: 5,
    name: "Cincinnati Cyclones",
    city: "Cincinnati",
    abbreviation: "CIN",
    division: "Central",
    conference: "Western",
    primaryColor: "#003DA5",
    secondaryColor: "#FC4C02",
    logoUrl: "https://assets.leaguestat.com/echl/logos/5.png",
  },
  8: {
    id: 8,
    name: "Florida Everblades",
    city: "Florida",
    abbreviation: "FLA",
    division: "South",
    conference: "Eastern",
    primaryColor: "#00703C",
    secondaryColor: "#C8A951",
    logoUrl: "https://assets.leaguestat.com/echl/logos/8.png",
  },
  60: {
    id: 60,
    name: "Fort Wayne Komets",
    city: "Fort Wayne",
    abbreviation: "FW",
    division: "Central",
    conference: "Western",
    primaryColor: "#F47920",
    secondaryColor: "#231F20",
    logoUrl: "https://assets.leaguestat.com/echl/logos/60.png",
  },
  108: {
    id: 108,
    name: "Greensboro Gargoyles",
    city: "Greensboro",
    abbreviation: "GRN",
    division: "South",
    conference: "Eastern",
    primaryColor: "#005EB8",
    secondaryColor: "#9B2335",
    logoUrl: "https://assets.leaguestat.com/echl/logos/108.png",
  },
  52: {
    id: 52,
    name: "Greenville Swamp Rabbits",
    city: "Greenville",
    abbreviation: "GVL",
    division: "South",
    conference: "Eastern",
    primaryColor: "#00563F",
    secondaryColor: "#A2AAAD",
    logoUrl: "https://assets.leaguestat.com/echl/logos/52.png",
  },
  11: {
    id: 11,
    name: "Idaho Steelheads",
    city: "Idaho",
    abbreviation: "IDH",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/11.png",
  },
  65: {
    id: 65,
    name: "Indy Fuel",
    city: "Indy",
    abbreviation: "IND",
    division: "Central",
    conference: "Western",
    primaryColor: "#002868",
    secondaryColor: "#BF0D3E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/65.png",
  },
  98: {
    id: 98,
    name: "Iowa Heartlanders",
    city: "Iowa",
    abbreviation: "IA",
    division: "Central",
    conference: "Western",
    primaryColor: "#00843D",
    secondaryColor: "#FFCD00",
    logoUrl: "https://assets.leaguestat.com/echl/logos/98.png",
  },
  79: {
    id: 79,
    name: "Jacksonville Icemen",
    city: "Jacksonville",
    abbreviation: "JAX",
    division: "South",
    conference: "Eastern",
    primaryColor: "#002868",
    secondaryColor: "#A2AAAD",
    logoUrl: "https://assets.leaguestat.com/echl/logos/79.png",
  },
  53: {
    id: 53,
    name: "Kalamazoo Wings",
    city: "Kalamazoo",
    abbreviation: "KAL",
    division: "Central",
    conference: "Western",
    primaryColor: "#E03A3E",
    secondaryColor: "#231F20",
    logoUrl: "https://assets.leaguestat.com/echl/logos/53.png",
  },
  56: {
    id: 56,
    name: "Kansas City Mavericks",
    city: "Kansas City",
    abbreviation: "KC",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#002868",
    secondaryColor: "#00843D",
    logoUrl: "https://assets.leaguestat.com/echl/logos/56.png",
  },
  101: {
    id: 101,
    name: "Maine Mariners",
    city: "Maine",
    abbreviation: "MNE",
    division: "North",
    conference: "Eastern",
    primaryColor: "#002868",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/101.png",
  },
  63: {
    id: 63,
    name: "Norfolk Admirals",
    city: "Norfolk",
    abbreviation: "NOR",
    division: "South",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/63.png",
  },
  13: {
    id: 13,
    name: "Orlando Solar Bears",
    city: "Orlando",
    abbreviation: "ORL",
    division: "South",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#A67C52",
    logoUrl: "https://assets.leaguestat.com/echl/logos/13.png",
  },
  85: {
    id: 85,
    name: "Rapid City Rush",
    city: "Rapid City",
    abbreviation: "RC",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#002868",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/85.png",
  },
  55: {
    id: 55,
    name: "Reading Royals",
    city: "Reading",
    abbreviation: "REA",
    division: "North",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/55.png",
  },
  97: {
    id: 97,
    name: "Savannah Ghost Pirates",
    city: "Savannah",
    abbreviation: "SAV",
    division: "South",
    conference: "Eastern",
    primaryColor: "#006341",
    secondaryColor: "#A2AAAD",
    logoUrl: "https://assets.leaguestat.com/echl/logos/97.png",
  },
  50: {
    id: 50,
    name: "South Carolina Stingrays",
    city: "South Carolina",
    abbreviation: "SC",
    division: "South",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/50.png",
  },
  109: {
    id: 109,
    name: "Tahoe Knight Monsters",
    city: "Tahoe",
    abbreviation: "TAH",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#B9975B",
    secondaryColor: "#231F20",
    logoUrl: "https://assets.leaguestat.com/echl/logos/109.png",
  },
  70: {
    id: 70,
    name: "Toledo Walleye",
    city: "Toledo",
    abbreviation: "TOL",
    division: "Central",
    conference: "Western",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/70.png",
  },
  103: {
    id: 103,
    name: "Trois-Rivières Lions",
    city: "Trois-Rivières",
    abbreviation: "TR",
    division: "North",
    conference: "Eastern",
    primaryColor: "#FFD700",
    secondaryColor: "#231F20",
    logoUrl: "https://assets.leaguestat.com/echl/logos/103.png",
  },
  72: {
    id: 72,
    name: "Tulsa Oilers",
    city: "Tulsa",
    abbreviation: "TUL",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#003DA5",
    secondaryColor: "#FF8200",
    logoUrl: "https://assets.leaguestat.com/echl/logos/72.png",
  },
  106: {
    id: 106,
    name: "Utah Grizzlies",
    city: "Utah",
    abbreviation: "UTA",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#002868",
    secondaryColor: "#A2AAAD",
    logoUrl: "https://assets.leaguestat.com/echl/logos/106.png",
  },
  61: {
    id: 61,
    name: "Wheeling Nailers",
    city: "Wheeling",
    abbreviation: "WHL",
    division: "North",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/61.png",
  },
  96: {
    id: 96,
    name: "Wichita Thunder",
    city: "Wichita",
    abbreviation: "WIC",
    division: "Mountain",
    conference: "Western",
    primaryColor: "#002868",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/96.png",
  },
  104: {
    id: 104,
    name: "Worcester Railers",
    city: "Worcester",
    abbreviation: "WOR",
    division: "North",
    conference: "Eastern",
    primaryColor: "#003DA5",
    secondaryColor: "#C8102E",
    logoUrl: "https://assets.leaguestat.com/echl/logos/104.png",
  },
};

// Lookup by name (for matching scraped names to IDs)
export const teamsByName = Object.fromEntries(
  Object.values(teams).map((t) => [t.name.toLowerCase(), t])
);

export function findTeamByName(name) {
  if (!name) return null;
  const lower = name.toLowerCase().trim();
  // Exact match
  if (teamsByName[lower]) return teamsByName[lower];
  // Partial match
  const entry = Object.values(teams).find(
    (t) =>
      lower.includes(t.city.toLowerCase()) ||
      lower.includes(t.name.toLowerCase()) ||
      t.name.toLowerCase().includes(lower)
  );
  return entry || null;
}
